name = "TOFtwin"
uuid = "fb4c2347-ef67-4041-8618-d5a4cc5ca4d8"
version = "1.0.0-DEV"
authors = ["Daniel Pajerowski <daniel@pajerowski.com>"]

[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
EzXML = "8f5d6c58-4d21-5cfd-889c-e3ad7ee6a615"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Sunny = "2b4a2ac8-8f8b-43e8-abf4-3cb0c45e8736"

[compat]
CairoMakie = "0.15.8"
EzXML = "1.2.3"
GLMakie = "0.13.8"
GeometryBasics = "0.5.10"
Interpolations = "0.16.2"
JLD2 = "0.6.3"
LinearAlgebra = "1.11.0"
Optim = "1.13.3"
Random = "1.11.0"
Revise = "3.12.3"
SHA = "0.7.0"
Serialization = "1.11.0"
SpecialFunctions = "2.6.1"
StaticArrays = "1.9.15"
Statistics = "1.11.1"
Sunny = "0.8.1"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
